### ISSUE TITLE
Does not work with jquery-pwstrength

### ISSUE THREAD

**Issue by wahmedswl** [dshemendiuk/gulp-npm-dist#14]
Hi, tried ```gulp-npm-dist``` with [```jquery-pwstrength```](https://github.com/matoilic/jquery.pwstrength) but failed with following error as it don't have ```dist``` folder and nor ```package.json```

```
Error: ENOENT: no such file or directory, open 'node_modules/jquery-pwstrength/package.json'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at module.exports (/home/gitlab/stisla/node_modules/gulp-npm-dist/index.js:70:33)
    at npm_modules (/home/gitlab/stisla/gulpfile.js:130:14)
    at bound (domain.js:420:14)
    at runBound (domain.js:433:12)
    at asyncRunner (/home/gitlab/stisla/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```
Thanks

**Comment by dshemendiuk** [comment]
How did you add this library? 
Can you give an example of package.json?

**Comment by wahmedswl** [comment]
Hi, sorry for late reply. Here is ```package.json```

```
{
  "name": "stisla-dev",
  "version": "1.0.0",
  "description": "Free Bootstrap Admin Template",
  "main": "index.js",
  "repository": "https://github.com/stisla/stisla",
  "author": "Stisla Team <nauvalazhar2@gmail.com> (https://getstisla.com)",
  "license": "MIT",
  "dependencies": {
    "@fortawesome/fontawesome-free": "^5.7.2",
    "bootstrap": "^4.2.1",
    "bootstrap-colorpicker": "^3.0.3",
    "bootstrap-daterangepicker": "^3.0.3",
    "bootstrap-social": "^5.1.1",
    "bootstrap-tagsinput": "^0.7.1",
    "bootstrap-timepicker": "^0.5.2",
    "chart.js": "^2.7.3",
    "chocolat": "^0.4.21",
    "cleave.js": "^1.4.7",
    "codemirror": "^5.43.0",
    "datatables": "^1.10.18",
    "datatables.net-responsive-bs4": "^2.2.3",
    "datatables.net-select-bs4": "^1.2.7",
    "dropzone": "^5.5.1",
    "flag-icon-css": "^3.2.1",
    "fullcalendar": "^3.10.0",
    "gmaps": "^0.4.24",
    "ionicons201": "1.0.0",
    "izitoast": "^1.4.0",
    "jquery": "^3.3.1",
    "jquery-pwstrength": "https://github.com/matoilic/jquery.pwstrength",
    "jquery-sparkline": "^2.4.0",
    "jquery-ui-dist": "^1.12.1",
    "jquery.nicescroll": "^3.7.6",
    "jquery_upload_preview": "https://github.com/opoloo/jquery_upload_preview",
    "jqvmap": "https://github.com/10bestdesign/jqvmap",
    "moment": "^2.24.0",
    "nicescroll": "^3.7.4",
    "owl.carousel": "^2.3.4",
    "perfect-scrollbar": "^1.4.0",
    "popper.js": "^1.14.7",
    "prismjs": "^1.15.0",
    "select2": "^4.0.6-rc.1",
    "selectric": "^1.13.0",
    "simpleweather": "^3.1.0",
    "sticky-kit": "^1.1.3",
    "summernote": "^0.8.11",
    "sweetalert": "^2.1.2",
    "tooltip.js": "^1.3.1",
    "weathericons": "^2.1.0"
  },
  "devDependencies": {
    "autoprefixer": "^9.4.7",
    "browser-sync": "^2.26.3",
    "cssnano": "^4.1.8",
    "gulp": "^4.0.0",
    "gulp-color": "^0.0.2",
    "gulp-concat": "^2.6.1",
    "gulp-imagemin": "^3.4.0",
    "gulp-notify": "^3.2.0",
    "gulp-nunjucks": "^4.0.0",
    "gulp-plumber": "^1.2.1",
    "gulp-postcss": "^8.0.0",
    "gulp-rename": "^1.4.0",
    "gulp-sass": "^4.0.2",
    "gulp-uglify": "^3.0.1",
    "gulp-uglify-es": "^1.0.4",
    "imagemin-mozjpeg": "^8.0.0",
    "nunjucks": "^3.1.7",
    "gulp-npm-dist": "^1.0.3"
  },
  "scripts": {
    "stisla-start": "yarn install --production=false",
    "stisla-dev": "yarn install --prod",
    "dist": "gulp dist",
    "dev": "gulp"
  }
}
```
Thanks

**Comment by BoPeng** [comment]
For anyone who might stumble into a similar problem, I had some package under `dependencies` and moving it to `devDependencies` solved the problem.
